apiVersion: v1
kind: Service   
metadata:
  name: flight-login-service
  labels:
    app: flight-login-service
spec:
  ports:
  - nodePort: 30703
    port: 7103
    targetPort: 7103
    protocol: TCP
  selector:
    app: flight-login-service
  type: LoadBalancer