apiVersion: v1
kind: Service   
metadata:
  name: flight-book-service
  labels:
    app: flight-book-service
spec:
  ports:
  - port: 7106
    targetPort: 7106
    protocol: TCP
  selector:
    app: flight-book-service