apiVersion: v1
kind: Service   
metadata:
  name: flight-registration-service
  labels:
    app: flight-registration-service
spec:
  ports:
  - port: 7104
    targetPort: 7104
    protocol: TCP
  selector:
    app: flight-registration-service