apiVersion: v1
kind: Service
metadata:
  name: flight-search-service
  labels:
    app: flight-search-service
spec:
  ports:
  - port: 7105
    targetPort: 7105
    protocol: TCP
  selector:
    app: flight-search-service